name       : python-jupyter_client
version    : 6.1.5
release    : 8
source     :
    - https://github.com/jupyter/jupyter_client/archive/6.1.5.tar.gz : e6b5bda078c6b2982f9095e833de4df6f0b8608c42340635b58e6a7d59174971
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter protocol client APIs
description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels. It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
builddeps  :
    - pkgconfig(python3)
    - python-ipykernel      # check
    - python-pytest         # check
rundeps    :
    - python3-ipython
    - python-dateutil
    - python-entrypoints
    - python-jupyter_core
    - python-pyzmq
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k 'not test_datetimes_msgpack'
