name       : python-jupyter_client
version    : 7.1.2
release    : 12
source     :
    - https://github.com/jupyter/jupyter_client/archive/refs/tags/v7.1.2.tar.gz : 2819c1355d257f1f5f6080b6178c24f413bf274646380ebf006c4ac1a8c8cad4
homepage   : https://github.com/jupyter/jupyter_client
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter protocol client APIs
description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels. It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
builddeps  :
    - pkgconfig(python3)
    - python-async-generator
    - python-ipykernel
    - python-pytest-asyncio
rundeps    :
    - python-dateutil
    - python-entrypoints
    - python-jupyter_core
    - python-pyzmq
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
