name       : python-jupyter_client
version    : 6.1.12
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyter_client/jupyter_client-6.1.12.tar.gz : c4bca1d0846186ca8be97f4d2fa6d2bae889cce4892a167ffa1ba6bd1f73e782
homepage   : https://github.com/jupyter/jupyter_client
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter protocol client APIs
description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels. It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
builddeps  :
    - pkgconfig(python3)
    - python-async-generator
    - python-ipykernel
    - python-pytest-asyncio
rundeps    :
    - python-dateutil
    - python-entrypoints
    - python-jupyter_core
    - python-pyzmq
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k 'not test_datetimes_msgpack'
