name       : python-jupyter_client
version    : 5.2.2
release    : 4
source     :
    - https://github.com/jupyter/jupyter_client/archive/5.2.2.tar.gz : 030a65d9e781313ee0e5244543a336bbfd50a6ba1f773924d9946a2918406388
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter protocol client APIs
description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels. It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-dateutil
    - python-entrypoints
    - python-jupyter_core
    - python-pyzmq
    - python-tornado
    - python-traitlets
setup      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
