name       : python-jupyter_client
version    : 8.2.0
release    : 18
source     :
    - https://github.com/jupyter/jupyter_client/releases/download/v8.2.0/jupyter_client-8.2.0.tar.gz : 9fe233834edd0e6c0aa5f05ca2ab4bdea1842bfd2d8a932878212fc5301ddaf0
homepage   : https://github.com/jupyter/jupyter_client
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter protocol client APIs
description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels. It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
builddeps  :
    - openssh               # check
    - python-build
    - python-hatchling
    - python-installer
    - python-packaging
    - python-ipykernel      # check
    - python-msgpack        # check
    - python-psutil         # check
    - python-pytest-asyncio # check
    - python-pytest-jupyter # check
    - python-pytest-timeout # check
rundeps    :
    - python-dateutil
    - python-jupyter_core
    - python-pyzmq
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v --deselect tests/test_localinterfaces.py::test_load_ips
