name       : python-jupyter_client
version    : 7.3.1
release    : 14
source     :
    - https://github.com/jupyter/jupyter_client/releases/download/v7.3.1/jupyter_client-7.3.1.tar.gz : 05d4ff6a0ade25138c6bb0fbeac7ddc26b5fe835e7dd816b64b4a45b931bdc0b
homepage   : https://github.com/jupyter/jupyter_client
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter protocol client APIs
description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels. It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
builddeps  :
    - pkgconfig(python3)
    - python-async-generator
    - python-ipykernel       # check
    - python-msgpack
    - python-psutil
    - python-pytest-asyncio  # check
    - python-pytest-timeout  # check
rundeps    :
    - python-dateutil
    - python-entrypoints
    - python-jupyter_core
    - python-pyzmq
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
