name       : python-jupyter_client
version    : 5.3.1
release    : 7
source     :
    - https://github.com/jupyter/jupyter_client/archive/5.3.1.tar.gz : aced0743cbb0c1449be7ef94bba89dc9661e050008cf15f906ae802c9c262cf8
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter protocol client APIs
description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels. It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-dateutil
    - python-entrypoints
    - python-ipython
    - python-jupyter_core
    - python-pyzmq
    - python-tornado
    - python-traitlets
setup      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
