name       : python-jupyter_client
version    : 7.3.5
release    : 16
source     :
    - https://github.com/jupyter/jupyter_client/releases/download/v7.3.5/jupyter_client-7.3.5.tar.gz : 3c58466a1b8d55dba0bf3ce0834e4f5b7760baf98d1d73db0add6f19de9ecd1d
homepage   : https://github.com/jupyter/jupyter_client
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter protocol client APIs
description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels. It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
    - python-jupyter_core   # check
    - python-packaging
    - python-ipykernel      # check
    - python-msgpack        # check
    - python-psutil         # check
    - python-pytest-asyncio # check
    - python-pytest-timeout # check
rundeps    :
    - python-dateutil
    - python-entrypoints
    - python-jupyter_core
    - python-pyzmq
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
