name       : python-jupyter_client
version    : 7.3.4
release    : 15
source     :
    - https://github.com/jupyter/jupyter_client/releases/download/v7.3.4/jupyter_client-7.3.4.tar.gz : aa9a6c32054b290374f95f73bb0cae91455c58dfb84f65c8591912b8f65e6d56
homepage   : https://github.com/jupyter/jupyter_client
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter protocol client APIs
description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels. It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
    - python-jupyter_core   # check
    - python-packaging
    - python-ipykernel      # check
    - python-msgpack        # check
    - python-psutil         # check
    - python-pytest-asyncio # check
    - python-pytest-timeout # check
rundeps    :
    - python-dateutil
    - python-entrypoints
    - python-jupyter_core
    - python-pyzmq
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
